### ISSUE TITLE
Not able to trigger a cloud function other than the cloud-build pub/sub topic.

### ISSUE THREAD

**Issue by ghost** [Ucnt/gcp-cloud-build-slack-notifier#1]
Hi  Ucnt,
             I have implemented notification using the cloud-build pub/subtopic, but when I try to use another topic(which is a log sink topic), which is not giving me any results. This is code will work only for the cloud build pub/sub topic or will it work for custom topic?.

**Comment by Ucnt** [comment]
Great question.  You can make it watch a custom topic if you change one of the below, depending on how you deployed it.

trigger-topic on line 9 or 18 of deploy_function.sh 

trigger-topic on line 13 of  cloudbuild.yaml

(note, I updated the documentation and code just now to allow for no secret manager to be used but putting the webhook directly in the code.)

**Comment by perdoorrajeshnayak** [comment]
Thank you so much ucnt. I have one question, can I use the above code in such a way that will Tigger a slack notification only for specific build_trigger_id?. Thanks in advance.

**Comment by Ucnt** [comment]
Yep. The JSON will have a key called buildTriggerId that you can filter on.
You'll just have to adjust to python code got look for that.

**Comment by ghost** [comment]
Hi Unct,
             When i tried with custom pub/sub topic ( other than the cloud-build topic), the cloud function will get invoked and but slack notification won't get triggered. (Custom topic is created using a log sink). And in logs, it is giving as Error: "logurl". Thanks in advance.
